# Custom Configuration File for LickCalc
# Copy this file and modify the values to set your preferred defaults
# Upload it using the "Load Config File" button in the app

session:
  bin_size: 300          # Default bin size for session histogram (seconds)
  fig_type: 'hist'      # Default figure type: 'hist' or 'cumul'
  length: 3600          # Default session length value (use 'auto' for automatic)
  length_unit: 's'      # Unit for session length: 's' (seconds), 'min' (minutes), or 'hr' (hours)

microstructure:
  interburst_interval: 0.5      # Default inter-burst interval (seconds)
  min_licks_per_burst: 1        # Minimum licks per burst
  long_lick_threshold: 0.3      # Long lick threshold (seconds)

files:
  default_file_type: 'dd'      # Default file type: 'med', 'csv', or 'dd'

# Note: The analysis section below defines slider ranges and is optional
# Only include these if you want to change the min/max ranges for sliders

analysis:
  max_session_bins: 300
  min_session_bins: 5
  session_bin_step: 5
  max_interburst_interval: 300.0
  min_interburst_interval: 0.0
  interburst_step: 10.0
  max_long_lick_threshold: 1.0
  min_long_lick_threshold: 0.1
  long_lick_step: 0.1
